<a href="https://colab.research.google.com/github/marialejandrapulido1/analitica-negocios/blob/main/Reto_1__MAPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importar librerías a utilizar

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB

Leer y cargar la base de datos

In [ ]:
data= "/content/1. BD2_CarCrash_Int.xlsx"ee
DF= pd.read_excel(data)

Quitar registros con datos faltantes

In [ ]:
DFP= DF.dropna()

Seleccionar datos de San Francisco

In [ ]:
DFP= DFP[DFP["County"]== "San Francisco"]

Convertir a valor numérico

In [ ]:
DFP["CrashType"]= pd.Categorical(DFP["CrashType"]).codes

Seleccionar datos que necesitamos

In [ ]:
DFP= DFP[['County','Weekday','ViolCat','ClearWeather','Month','Daylight','CrashType','Highway']]


Organizar y filtrar en el orden que necesitamos

In [ ]:
XDD= DFP[['Weekday','ViolCat','ClearWeather','Month','CrashType','Daylight']]
YDD= DFP['Highway']

Usar Naive Bayes

In [ ]:
mnb= GaussianNB()
mnb.fit(XDD, YDD)

GaussianNB()

Encontrar la media

In [ ]:
media= mnb.theta_
print("la media de las variables a averiguar son:", media)

la media de las variables a averiguar son: [[3.88417722 7.45696203 0.86265823 4.35189873 3.21772152 0.66265823]
 [3.9261477  4.1497006  0.79840319 6.69461078 2.27744511 0.62075848]]


Encontrar la standard deviation

In [ ]:
sd= mnb.var_
sd= np.sqrt(sd)
print("la deviacion estandar de las variables son:", sd)


la deviacion estandar de las variables son: [[1.95062542 3.52136997 0.34420782 2.3433645  1.87371962 0.47280262]
 [2.01603723 2.16198902 0.40119266 3.44163641 1.05765448 0.48519831]]


Encontrar limite superior

In [ ]:
LS= media+sd
print("los limites superiores son:", LS)

los limites superiores son: [[ 5.83480263 10.978332    1.20686605  6.69526323  5.09144114  1.13546084]
 [ 5.94218494  6.31168962  1.19959585 10.13624719  3.33509959  1.10595679]]


Encontrar limite inferior

In [ ]:
LI= media-sd
print("los limites inferiores son:", LI)

los limites inferiores son: [[1.9335518  3.93559205 0.51845041 2.00853424 1.3440019  0.18985561]
 [1.91011047 1.98771158 0.39721054 3.25297437 1.21979063 0.13556017]]


Encontrar intervalos positivos y negativos

In [ ]:
YDP= mnb.predict(XDD)
confmat= confusion_matrix(YDD, YDP)
print(confmat)

VN= confmat[0,0]
FP= confmat[0,1]
FN= confmat[1,0]
VP= confmat[1,1]
print("VN =",VN,"FP =",FP,"FN =",FN,"VP =",VP)


[[1365  215]
 [ 224  277]]
VN = 1365 FP = 215 FN = 224 VP = 277


Encontrar exactitud alcanzada

In [ ]:
exact= (VP+VN)/len(XDD)
print("la exactitud es:", exact)

la exactitud es: 0.7890437289764536


Encontrar especificidad alcanzada

In [ ]:
especi= VN/(VN+FN)
print("la especificidad del modelo es:", especi)

la especificidad del modelo es: 0.8590308370044053


Encontrar tasa de error alcanzada

In [ ]:

tasa= (FP+FN)/len(XDD)
print("la tasa de error del modelo es:", tasa)

la tasa de error del modelo es: 0.21095627102354636


Encontrar sensibilidad alcanzada

In [ ]:
sensi= VP/(VP+FN)
print("la sensibilidad del modelo es:", sensi)

la sensibilidad del modelo es: 0.5528942115768463


Encontrar la presición alcanzada

In [ ]:
pres= VP/(VP+FP)
print("la precisión del modelo es:", pres)

la precisión del modelo es: 0.5630081300813008


Encontrar la predicción negativa

In [ ]:
prednega= VN/(VN+FN)
print("la predicción negativa del modelo es:", prednega)

la predicción negativa del modelo es: 0.8590308370044053


Indicar categoria de la persona

In [ ]:
XSC= [[5,1,1,3,4,0]]
ydsc= mnb.predict(XSC)
print("la predicción del modelo es:", ydsc)

la predicción del modelo es: [0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


Numero, separación y división de datos

In [ ]:
ct= mnb.class_count_
print ("separación de los datos:", ct)
print ("total datos", len(XDD))
print ("división porcentual de datos:", ct/len(XDD))

separación de los datos: [1580.  501.]
total datos 2081
división porcentual de datos: [0.75925036 0.24074964]


In [ ]:
XSC= [[5,1,1,3,4,0]]
ydsc= mnb.predict(XSC)
print("la predicción del modelo es:", ydsc)

la predicción del modelo es: [0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
